#!/bin/bash -x


# Create hosts
ip netns add h0
ip netns add h1
ip netns add h2
ip netns add h3
ip netns add h4
ip netns add h5
ip netns add h6
ip netns add h7
ip netns add h8
ip netns add h9
ip netns add h10


# Create switches
ovs-vsctl add-br s1


# Create links between hosts and switches
ip link add h0-eth0 type veth peer name s1-h0
ip link add h1-eth0 type veth peer name s1-h1
ip link add h2-eth0 type veth peer name s1-h2
ip link add h3-eth0 type veth peer name s1-h3
ip link add h4-eth0 type veth peer name s1-h4
ip link add h5-eth0 type veth peer name s1-h5
ip link add h6-eth0 type veth peer name s1-h6
ip link add h7-eth0 type veth peer name s1-h7
ip link add h8-eth0 type veth peer name s1-h8
ip link add h9-eth0 type veth peer name s1-h9
ip link add h10-eth0 type veth peer name s1-h10

# Create links between VM host and switches
ip link add host-eth0 type veth peer name s1-host


# Associate links to namespaces
ip link set h0-eth0 netns h0
ip link set h1-eth0 netns h1
ip link set h2-eth0 netns h2
ip link set h3-eth0 netns h3
ip link set h4-eth0 netns h4
ip link set h5-eth0 netns h5
ip link set h6-eth0 netns h6
ip link set h7-eth0 netns h7
ip link set h8-eth0 netns h8
ip link set h9-eth0 netns h9
ip link set h10-eth0 netns h10

# Connect the links to switch
ovs-vsctl add-port s1 s1-h0
ovs-vsctl add-port s1 s1-h1
ovs-vsctl add-port s1 s1-h2
ovs-vsctl add-port s1 s1-h3
ovs-vsctl add-port s1 s1-h4
ovs-vsctl add-port s1 s1-h5
ovs-vsctl add-port s1 s1-h6
ovs-vsctl add-port s1 s1-h7
ovs-vsctl add-port s1 s1-h8
ovs-vsctl add-port s1 s1-h9
ovs-vsctl add-port s1 s1-h10
ovs-vsctl add-port s1 s1-host

# Activate namespace root
ip link set dev s1-h0 up
ip link set dev s1-h1 up
ip link set dev s1-h2 up
ip link set dev s1-h3 up
ip link set dev s1-h4 up
ip link set dev s1-h5 up
ip link set dev s1-h6 up
ip link set dev s1-h7 up
ip link set dev s1-h8 up
ip link set dev s1-h9 up
ip link set dev s1-h10 up

# Activate namespace root VM host
ip link set dev s1-host up


# Activate interfaces of namespaces h0-h10
ip netns exec h0 ip link set dev h0-eth0 up
ip netns exec h1 ip link set dev h1-eth0 up
ip netns exec h2 ip link set dev h2-eth0 up
ip netns exec h3 ip link set dev h3-eth0 up
ip netns exec h4 ip link set dev h4-eth0 up
ip netns exec h5 ip link set dev h5-eth0 up
ip netns exec h6 ip link set dev h6-eth0 up
ip netns exec h7 ip link set dev h7-eth0 up
ip netns exec h8 ip link set dev h8-eth0 up
ip netns exec h9 ip link set dev h9-eth0 up
ip netns exec h10 ip link set dev h10-eth0 up

# Set default ip address of namespace VM host
ip link set dev host-eth0 up

ip netns exec h0 ip link set dev lo up
ip netns exec h1 ip link set dev lo up
ip netns exec h2 ip link set dev lo up
ip netns exec h3 ip link set dev lo up
ip netns exec h4 ip link set dev lo up
ip netns exec h5 ip link set dev lo up
ip netns exec h6 ip link set dev lo up
ip netns exec h7 ip link set dev lo up
ip netns exec h8 ip link set dev lo up
ip netns exec h9 ip link set dev lo up
ip netns exec h10 ip link set dev lo up

ip link set dev lo up

# Set default ip address of namespace VM host
ip a add dev host-eth0 10.10.10.1/24

sudo sysctl -w net.ipv4.conf.all.forwarding=1

#ip netns exec h0 ip a add dev h0-eth0 10.10.10.2/24

