#!/bin/bash -x
sudo iptables -P FORWARD DROP
sudo iptables -t filter -A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT
#sudo iptables -t nat -A POSTROUTING -s 10.10.10.0/24 -j MASQUERADE

#sudo iptables -t filter -A FORWARD -s 10.10.10.0/24 -j ACCEPT
#sudo iptables -t filter -A FORWARD -d 10.10.10.0/24 -j ACCEPT
sudo iptables -t nat -A PREROUTING -s 10.10.10.0/24 -p tcp --dport 443 -j REDIRECT --to-ports 8080
sudo iptables -t nat -A PREROUTING -s 10.10.10.0/24 -p tcp --dport 80 -j REDIRECT --to-ports 8080

sudo iptables -t nat -A PREROUTING -s 10.10.10.0/24 -p udp --dport 53 -j DNAT --to 10.10.10.1
